### ISSUE TITLE
normalize file path exception 'utf-8' codec can't decode byte 0xe1 in position 7: invalid continuation byte, input_file_path: "Get_krv\341canie_LMWH.ipynb"

### ISSUE THREAD

**Issue by terxw** [MestreLion/git-tools#59]
I got this error while trying git commit with precommit hook
```
git-restore-mtime -v 
```

filename is

```
Get_krvácanie_LMWH.ipynb
```

escaped as 

```
Get_krv\341canie_LMWH.ipynb
```

Whole error is:

```
Traceback (most recent call last):
  File "/usr/lib/git-core/git-restore-mtime", line 413, in <module>
    sys.exit(main())
  File "/usr/lib/git-core/git-restore-mtime", line 368, in main
    parselog(filelist, dirlist, stats, git, args.merge, args.pathspec)
  File "/usr/lib/git-core/git-restore-mtime", line 274, in parselog
    file = normalize(file)
  File "/usr/lib/git-core/git-restore-mtime", line 189, in normalize
    .decode('utf8'))           # Decode from UTF-8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 7: invalid continuation byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_git-core_git-restore-mtime.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/git-core/git-restore-mtime", line 413, in <module>
    sys.exit(main())
  File "/usr/lib/git-core/git-restore-mtime", line 368, in main
    parselog(filelist, dirlist, stats, git, args.merge, args.pathspec)
  File "/usr/lib/git-core/git-restore-mtime", line 274, in parselog
    file = normalize(file)
  File "/usr/lib/git-core/git-restore-mtime", line 189, in normalize
    .decode('utf8'))           # Decode from UTF-8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 7: invalid continuation byte
```

I can recreate the error in python console:

```
path = "\"Get_krv\341canie_LMWH.ipynb\""
path = (path[1:-1].encode('latin1').decode('unicode-escape')) 
path
#'Get_krvácanie_LMWH.ipynb'
path.encode('latin1').decode('utf8')
#Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
#UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 7: invalid continuation byte

```

**Comment by MestreLion** [comment]
What version of `git-restore-mtime` are you using? I believe you might be using an outdated version, as this bug was fixed a few years ago. Care to test with latest release?

**Comment by terxw** [comment]
Yes, it was older version in system path, thought that i was using newest in hook s dir...
